### PR TITLE
Update to Roundcube 1.1.1

### PR DESCRIPTION
**Pull request by jeromelebleu**
* Download sources instead of having them in sources/
* Use the new config.inc.php conf file without redefining unmodified parameters
* Purpose the installation of an experimental *calendar* plugin with CalDav sync

The *calendar* plugin is based on http://git.kolab.org/roundcubemail-plugins-kolab/tag/?id=roundcubemail-plugins-kolab-3.2.7 with the caldav driver from https://gitlab.awesome-it.de/kolab/roundcube-plugins/tree/feature_caldav. I'll surely host this code in a git repository.

It's a work-in-progress update proposal and have to be improved - e.g. checking the downloaded files sums.

### CODE REVIEW

**Comment by Kloadut** [comment]
Is it mergeable ?

**Comment by polytan02** [comment]
Roundcube 1.1.2 is available

**Comment by julienmalik** [comment]
roundcube 1.1.3 now

**Comment by polytan02** [comment]
I have the official roundcube installed. How to upgrade to this test version please ?

**Comment by jeromelebleu** [comment]
I've rebased the master branch to this one and move it instead on the [*calendar* branch](https://github.com/jeromelebleu/roundcube_ynh/tree/calendar). However I'll not update it anymore and I'm working instead on [this branch](https://github.com/jeromelebleu/roundcube_ynh/tree/1.1.x) which need current testing version of YunoHost.
To upgrade your Roundcube installation to those versions, you can try - but I've never tried with a specific branch, not sure it will work:
`sudo yunohost app upgrade roundcube --url <git_repo_url>`

**Pull request closed without merging**
